# Generated by Django 4.2 on 2023-04-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstOne', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='People',
            new_name='BAZA',
        ),
    ]
