# Generated by Django 4.2 on 2023-04-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstOne', '0002_rename_people_baza'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHYNGYZ_AITMATOV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chyngyz_Aitmatov', models.CharField(max_length=255)),
                ('year_of_brith', models.DateTimeField()),
                ('Year_of_death', models.DateTimeField(blank=True)),
                ('Biogarfia', models.TextField()),
                ('Detstvo_unost', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='DETSTVO_UNOST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chyngyz_Aitmatov', models.CharField(max_length=255)),
                ('year_of_brith', models.DateTimeField()),
                ('Year_of_death', models.DateTimeField(blank=True)),
                ('Biogarfia', models.TextField()),
                ('Detstvo_unost', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LICHNAYA_LIFE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=255)),
                ('year_of_brith', models.DateTimeField()),
                ('Year_of_death', models.DateTimeField(blank=True)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LITERATURA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TEXT', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PHOTO_KARUSEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='BAZA',
            new_name='BIOGRAFY',
        ),
    ]
